name: Auto-merge

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
      - ready_for_review
    branches:
      - main
  check_suite:
    types:
      - completed
    status:
      - success

permissions:
  pull-requests: write
  contents: read

jobs:
  auto_merge:
    if: |
      github.event_name == 'pull_request' &&
      contains(join(github.event.pull_request.labels.*.name, ','), 'Ready to merge') &&
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.SERVICE_TOKEN }}

      - name: Rebase, enable auto-merge or merge pull request
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.SERVICE_TOKEN }}
        run: |
          gh pr update-branch $PR_NUMBER --rebase
          gh pr merge $PR_NUMBER --auto -s -d
